version: "3"
services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: pg_password
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
  materialized:
    image: materialize/materialized
    container_name: materialized
    restart: always
    ports:
      - 6875:6875
    depends_on:
      - postgres
  helper:
    container_name: helper
    build:
      context: ./helper
    depends_on:
      - materialized
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 4000:4000
    depends_on:
      - materialized
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
