version: "3"
services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: pg_password
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
  materialized:
    image: materialize/materialized:v0.20.0
    container_name: materialized
    restart: always
    ports:
      - 6875:6875
    depends_on:
      - postgres
  grafana_dashboard:
    image: materialize/dashboard
    container_name: grafana_dashboard
    restart: always
    ports:
      - 3001:3000
    depends_on:
      - materialized
    environment:
      MATERIALIZED_URL: materialized:6875
  metabase:
    image: iwalucas/metabase
    container_name: metabase
    depends_on:
      - materialized
    ports:
      - 3030:3000
networks:
  default:
    external:
      name: custom-driver
